name: qyran
description: "Qyran project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  responsive_sizer: ^3.3.1
  google_fonts: ^6.2.1
  slide_switcher: ^1.1.2
  flutter_chat_bubble: ^2.0.2
  flutter_svg: ^2.0.10+1
  pinput: ^4.0.0
  motion_toast: ^2.9.1
  flashy_tab_bar2: ^0.0.10
  percent_indicator: ^4.2.3
  smooth_page_indicator: ^1.1.0
  retrofit: '>=4.0.0 <5.0.0'
  json_annotation: ^4.8.1
  intl: ^0.18.1
  intl_utils: ^2.8.7
  dio: ^5.4.3+1
  loader_overlay: ^4.0.0
  url_launcher: ^6.2.6
  youtube_player_flutter: ^8.1.2
  image_picker: ^1.1.1
  animated_list_plus: ^0.5.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: '>=7.0.0 <8.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_intl:
  enabled: true
  main_locale: ru